# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Data-Driven Analytics
tagline:          'Data Science and Analytics'
description:      '<a href="https://www.linkedin.com/in/akhil-sreehari-aa8b20a0" target="_blank">@Akhil Sreehari</a>
                  Just a bunch of my experiments playing around with datasets.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Akhil Sreehari'
  url:            https://www.linkedin.com/in/akhil-sreehari-aa8b20a0

paginate:         5

# Custom vars
version:          master

github:
  repo:           https://github.com/akhil-sreehari/akhil-sreehari.github.io

relative_permalinks: false
